blank_issues_enabled: false
contact_links:
  - name: â“ Help and Support Slack Channel
    url: https://tinyurl.com/rethinkdb-slack
    about: Please ask and answer questions here. ğŸ¥
  - name: â“ Help and Support Discord Channel
    url: https://discord.gg/ZeEq5TE
    about: Please ask and answer questions here. ğŸ¥